### ISSUE TITLE
Database Query Error

### ISSUE THREAD

**Issue by ExplodingDragon** [ibadboy-net/ByeTyp#7]
PHP 版本:5.6

SQL版本：SQLite

错误日志为 

```text
SQLSTATE[HY000]: General error: 1 near "separator": syntax error
Typecho_Db_Query_Exception: SQLSTATE[HY000]: General error: 1 near "separator": syntax error in /www/wwwroot/OldBlog/var/Typecho/Db/Adapter/Pdo.php:105
Stack trace:
#0 /www/wwwroot/OldBlog/var/Typecho/Db.php(353): Typecho_Db_Adapter_Pdo->query()
#1 /www/wwwroot/OldBlog/usr/plugins/ByeTyp/Action.php(172): Typecho_Db->query()
#2 /www/wwwroot/OldBlog/usr/plugins/ByeTyp/Action.php(18): ByeTyp_Action->wxr_posts_list()
#3 /www/wwwroot/OldBlog/usr/plugins/ByeTyp/Action.php(90): ByeTyp_Action->doExport()
#4 /www/wwwroot/OldBlog/var/Widget/Do.php(82): ByeTyp_Action->action()
#5 /www/wwwroot/OldBlog/var/Typecho/Widget.php(221): Widget_Do->execute()
#6 /www/wwwroot/OldBlog/var/Typecho/Router.php(135): Typecho_Widget::widget()
#7 /www/wwwroot/OldBlog/index.php(23): Typecho_Router::dispatch()
#8 {main}
```

**Comment by sunxiyuan** [comment]
加一下我QQ：1642491905，我远程调试下

**Comment by ExplodingDragon** [comment]
> 加一下我QQ：1642491905，我远程调试下

啊，我已经用 SQL 导出了，现在没问题了...
